server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**

        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/products/**

        - id: inventory-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/inventories/**

        - id: billing-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/billing/**

        - id: merchant-order-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/merchant-orders/**

        - id: order-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/orders/**

        - id: notification-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/notifications/**

        - id: audit-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/audit-logs/**

        - id: analytics-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/analytics/**
